spring:
  application:
    name: Xmap-API

  liquibase:
    enabled: true
    default-schema: public
    change-log: classpath:db/changelog/main-changelog.xml

  datasource:
    url: jdbc:postgresql://localhost:5432/xmap
    username: xmap_admin
    password: 123

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8082
  address: 0.0.0.0
  tomcat:
    max-swallow-size: -1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

xmap-api:
  base-url: "http://172.20.10.3:8082"
  s3-file:
    # URN (Uniform Resource Name) - URL без scheme (без http://)
    download-link-template: "/api/s3-file/{id}"
    download-link-path-param: "{id}"
