--liquibase formatted sql
--changeset Shulpov Victor:20241111215937-add-spot-table splitStatements:true
CREATE TABLE spot(
                     id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     "name" varchar(50) NOT NULL,
                     lat DOUBLE PRECISION NOT NULL,
                     lon DOUBLE PRECISION NOT NULL,
                     accepted BOOLEAN NOT NULL DEFAULT FALSE,
                     adding_date TIMESTAMP NOT NULL DEFAULT now(),
                     updating_date TIMESTAMP DEFAULT now(),
                     description varchar(300) NOT NULL
);