- name: Restart only app (handler)
  become: yes
  ansible.builtin.shell: |
    cd {{ deploy_path }}
    docker compose stop app
    docker compose rm -f app
    docker compose up -d --build
  args:
    chdir: "{{ deploy_path }}"